# Dockerfile for Django Applications

# Section 1- Base Image
FROM python:3.11.2-slim
RUN apt update && apt upgrade -y
RUN mkdir app/
COPY . /app/
WORKDIR /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD python manage.py runserver && stripe listen --forward-to localhost:8000/webhooks/stripe