# Dockerfile for Django Applications

# Section 1- Base Image
FROM python:3.11.2-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ARG production
ENV production=$production
ARG SECRET_KEY
ENV SECRET_KEY=$SECRET_KEY
ARG DB_HOST
ENV DB_HOST=$DB_HOST
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG EMAIL_HOST
ENV EMAIL_HOST=$EMAIL_HOST
ARG EMAIL_HOST_USER
ENV EMAIL_HOST_USER=$EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ENV EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
ARG STRIPE_PUBLIC_KEY
ENV STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
ARG STRIPE_SECRET_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK
ENV STRIPE_WEBHOOK=$STRIPE_WEBHOOK
ARG STRIPE_PRODUCT_ID
ENV STRIPE_PRODUCT_ID=$STRIPE_PRODUCT_ID
ARG STRIPE_PRICE_ID
ENV STRIPE_PRICE_ID=$STRIPE_PRICE_ID
ENV HOME=/home/app
ENV APP_HOME=/home/app/web

RUN mkdir $HOME
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME
RUN apt update && apt upgrade -y
RUN apt install libpq-dev gcc iputils-ping -y
RUN pip install -U pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN python manage.py collectstatic --noinput
