# Generated by Django 4.1.2 on 2022-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EmailClient',
            new_name='Newsletter',
        ),
    ]
