# Generated by Django 4.1.5 on 2023-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_client_rename_emailclient_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
