# Generated by Django 4.1.5 on 2023-04-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='concert.product'),
            preserve_default=False,
        ),
    ]
