# Generated by Django 4.1.5 on 2023-04-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
