# Generated by Django 4.1.5 on 2023-01-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
