# Generated by Django 4.1.5 on 2023-01-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_delete_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
