name: Django CI

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    - name: Heroku Django Deploy
      uses: nyakaz73/heroku-django-deploy@v0.81
      with: 
        heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email_address: 'gouverneur.martin@hotmail.com'
        use_git: true
        git_branch: master


