name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: martingouv
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      run: docker buildx create --name builder --use
    - name: Build and push the Docker images
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t martingouv/concert --push --file Dockerfile .
