name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: martingouv
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        build-args: |
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_PRIVATE_KEY }}
          STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_WEBHOOK=${{ secrets.STRIPE_WEBHOOK }}
          EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          STRIPE_PRODUCT_ID=${{ secrets.STRIPE_PRODUCT_ID }}
          STRIPE_PRICE_ID=${{ secrets.STRIPE_PRICE_ID }}
          production=true
        push: true
        tags: martingouv/concert:latest
        platforms: "linux/amd64,linux/arm/v7"
    

