name: Building production images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: martingouv
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push 1
      uses: docker/build-push-action@v3
      with:
        context: .
        build-args: |
          production=1
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_PRIVATE_KEY }}
          STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_WEBHOOK=${{ secrets.STRIPE_WEBHOOK }}
          STRIPE_PRODUCT_ID=${{ secrets.STRIPE_PRODUCT_ID }}
          STRIPE_PRICE_ID=${{ secrets.STRIPE_PRICE_ID }}
        push: true
        tags: martingouv/concert:latest
        platforms: "linux/amd64 ,linux/arm/v7, linux/arm64/v8"
    - name: Build and push 2
      uses: docker/build-push-action@v3
      with:
        context: ./nginx
        push: true
        tags: martingouv/concert:nginx
        platforms: "linux/amd64 ,linux/arm/v7, linux/arm64/v8"

    - name: Build and push 3
      uses: docker/build-push-action@v3
      with:
        context: ./stripe-cli
        push: true
        tags: martingouv/concert:stripe
        platforms: "linux/amd64 ,linux/arm/v7, linux/arm64/v8"

        

    

